# Generated by Django 4.1.7 on 2023-07-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_remove_audio_note_audio_audio_note_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_note',
            name='audio_file',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
